CREATE TABLE [dbo].[Courses] (
	[CourseId] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
	[CourseTitle] VARCHAR(500) NOT NULL,
	[CourseCategory] VARCHAR(200) NULL,
	[CourseDescription] NVARCHAR(MAX) NULL,
	[CourseDisplayImg] NVARCHAR(MAX) NULL,
	[CourseCoverImg] NVARCHAR(MAX) NULL,
	[CourseState] VARCHAR(250) NULL DEFAULT 'OPEN',
	[DateCreated] DATETIME NOT NULL DEFAULT GETDATE(),
	[DateUpdated] DATETIME NOT NULL DEFAULT GETDATE(),

    CONSTRAINT [PK_Courses] PRIMARY KEY CLUSTERED ([CourseId] ASC)
);