CREATE TABLE [dbo].[UserCourses] (
	[CourseId] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
	[UserId] NVARCHAR(128) NOT NULL,
	[Status] VARCHAR(500) NULL,
	[DateEnrolled] DATETIME NOT NULL DEFAULT GETDATE(),
	[DateCompleted] DATETIME NULL,

    CONSTRAINT [PK_UserCourses] PRIMARY KEY CLUSTERED ([CourseId] ASC, [UserId] ASC),
	CONSTRAINT [FK_CourseUser] FOREIGN KEY ([UserId]) REFERENCES [dbo].[Users]([Id]) ON DELETE CASCADE
);